name: reddit_task
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bottom_sheet: ^4.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dropdown_button3: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  google_fonts: ^6.1.0
  responsive_builder: ^0.7.0
  svg_flutter: ^0.0.1
  video_player: ^2.8.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
